<a href="https://colab.research.google.com/github/zeshmzm/NLP-Projects-Tasks/blob/main/NLP_Classification_HF_Torch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import torch
from torch import nn
import numpy as np


In [ ]:
data = [[1,2,3,4],[5,6,7,8]]

data_t = torch.tensor(data)

In [ ]:
data_t

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [ ]:
t1 = torch.randn(3,4)
t2 = torch.randn(4)
t3 = torch.matmul(t1,t2)
t3

tensor([-0.6814,  1.4799,  0.2746])

In [3]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification, DistilBertForSequenceClassification, DistilBertTokenizer, BertTokenizer
model_name = 'distilbert-base-uncased-finetuned-sst-2-english'
pt_model = AutoModelForSequenceClassification.from_pretrained(model_name)






config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/268M [00:00<?, ?B/s]

In [4]:
tokenizer = AutoTokenizer.from_pretrained(model_name)

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [8]:
sentence_pos = 'Liverpool FC is the best team in the world and I am ecstatic to hear that'
sentence_neg = 'Manchester United are the worst side and I hate them'
inputs_pos = tokenizer(sentence_pos)
inputs_neg = tokenizer(sentence_neg)

In [12]:
inputs_neg

{'input_ids': [101, 5087, 2142, 2024, 1996, 5409, 2217, 1998, 1045, 5223, 2068, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [13]:
tokenizer.convert_ids_to_tokens([5409, 2217, 1998, 1045, 5223])

['worst', 'side', 'and', 'i', 'hate']

In [14]:
pt_batch = tokenizer(
    [sentence_pos, sentence_neg],
    padding= True,
    truncation = True,
    max_length = 512,
    return_tensors = 'pt'
)

In [15]:
pt_batch

{'input_ids': tensor([[  101,  6220,  4429,  2003,  1996,  2190,  2136,  1999,  1996,  2088,
          1998,  1045,  2572, 14925, 16677,  2000,  2963,  2008,   102],
        [  101,  5087,  2142,  2024,  1996,  5409,  2217,  1998,  1045,  5223,
          2068,   102,     0,     0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0]])}

In [17]:
pt_outputs = pt_model(**pt_batch)
pt_outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-4.2119,  4.5930],
        [ 4.5998, -3.7500]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [20]:
pt_predictions = nn.functional.softmax(pt_outputs.logits, dim= 1)

In [29]:
pt_predictions.detach().numpy()

array([[0.00014998, 0.99985003],
       [0.99976367, 0.00023639]], dtype=float32)

In [28]:

np.set_printoptions(suppress=True)
